config/routes.rb
# Entire routes.rb is calling draw method with do-end block
SampleApp::Application.routes.draw do

  devise_for :users, controllers: { confirmations: 'confirmations' }

  # From API: resources(*resources, &block)
  # * called splat operator. It indicates that mrore parameters may be passed to the function.
  # And those parameters are collected up and an array is created.
  # do...end or {} is called "block" which contains several lines of code and can be executed with "yield".
  # do...end for multi-lines blocks and {} for single line blocks
  # block is associated with method invocation. 
  # e.g. greet {put 'Hello'} invokes a call to greet method with block {put 'Hello'}.
  # Basically, when you create a method, you can have several yield statement. 
  # Then if you invoke that method with blcok, the block is executed.

  resources :sessions, only: [:new, :create, :destroy]
  resources(:microposts) do
    post :vote, on: :member
    delete :delete, on: :member
  end
  
  resources :users

  resources :password_resets
  
  root to: 'static_pages#home'
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/sendmessage', to: 'microposts#new'
  get '/help',    to: 'users#help'
  delete '/removepost', to: 'microposts#destroy'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  #attr_accessible :content, :email, :tag

  belongs_to :user
  has_many :votes

  validates :content, presence: true, length: { maximum: 500 }
  validates :tag, presence: true

  # /.../i is case insensitve

  # $ indicates the end of line and is bad because it allows javascript injection.
  # e.g. "matchedString\n<script>code</script>" will pass regex check because of new line char \n
  # so we want to use \z instead of $. Same reason for using \A instead of ^
  
  # \. escapes dot
  # \d is digit
  # [a-zA-Z] char set is not equivalent to [A-z]. And [a-Z] is not valid at all.
  # A wider option is \w which is a character from a-z, A-Z, 0-9, including the _ (underscore) character.
  # VALID_EMAIL_REGEX = /\A[a-z]+\.\d+@osu.edu|admin\z/
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :user_id, presence: true
  default_scope { order(:created_at => :desc) }

  def count_votes
  	read_attribute(:votes) || votes.sum(:value)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :signed_in_user, only: [:create, :destroy, :index]
	before_action :correct_user, only: :destroy

	def create

		if !params[:micropost][:email].empty? && !params[:micropost][:tag].empty?
			# if this message is sent to a specific person

			@user = User.where("email = ?", params[:micropost][:email]).first

			if !@user.nil?
				# Find all receiver's microposts.
				@receiver_posts = Micropost.where("user_id = ?", @user[:id])
		
				# Find all the microposts which receiver wants to send to sender.
				@match_posts = @receiver_posts.where("email = ?", current_user.email)
		
				#Find the final micropost which will be sent to sender. 
				@final_post = @match_posts.where(["tag = ?", params[:micropost][:tag]]).first
			end
		end
		
		@micropost = current_user.microposts.build(micropost_params)

		@micropost[:sender_email] = current_user.email
		
		# We find some match post
		if !@final_post.nil?
			MicropostMailer.find_match(@user, current_user, @micropost).deliver
			MicropostMailer.find_match(current_user, @user, @final_post).deliver
			
			@final_post.update_attribute(:match, true)
			@micropost.update_attribute(:match, true)
		end

		if @micropost.save
			if params[:micropost][:email].empty?
				@post = @micropost
			else
				@post = nil
			end
			flash.now[:notice] = "Message sent successfully."
		else 
			flash.now[:notice] = "Message sent unsuccessfully. Please try again."
		end
	end

	def index 
		@mails = Micropost.where("email = ? and match IS TRUE", current_user.email)
		render 'microposts/inbox'
	end 

	def destroy
		@matched_receiver = User.where("email = ?", @micropost[:email]).first
		if !@matched_receiver.nil?
			@matched_receiver_posts = Micropost.where("user_id = ?", @matched_receiver[:id])
			@matched_posts = @matched_receiver_posts.where("email = ?", current_user.email)
			@final_matched_post = @matched_posts.where("tag = ?", @micropost[:tag]).first
			@final_matched_post.update_attribute(:match, false) if !@final_matched_post.nil?
		end
		@micropost.destroy
		redirect_to current_user
	end

	# In this funtion, you should use current_user.microposts.build, instead of current_user.microposts.new,
	# even though new and build have the same functionality. 
	# current_user.microposts.new will cause stack overflow due to infinite recursion because the method name is also "new".
	def new
    	@feed_items = Micropost.where("email = ''").page(params[:page]).per_page(15)
    	@micropost = current_user.microposts.build
    	@user = current_user
  	end

	def mark_as_read
		@read_notification = Micropost.where("id = ?", params[:id])
		@read_notification.update_attribute(:read, true)
	end

	def vote
		# new(attributes = nil, options = {})
		# e.g. Instantiate a single object by passing mass-assignment security
		# User.new({ :first_name => 'Jamie', :is_admin => true }, :without_protection => true)

    	@vote = current_user.votes.new(value: params[:value], micropost_id: params[:id])
        @vote.save
        @count = params[:count].to_i + params[:value].to_i
  	end

  	def delete
  		vote = Vote.where("micropost_id = ? and user_id = ?", params[:id], current_user.id).first
  		@count_delete = params[:count].to_i - vote.value.to_i
  		@micropost = Micropost.where("id = ?", params[:id]).first
  		vote.destroy
  	end
  	
	private
		def correct_user
			@micropost = current_user.microposts.find_by_id(params[:id])
			redirect_to root_path if @micropost.nil?
		end

  		# Action Controller parameters are forbidden to be used in Active Model mass assignments 
  		# until they have been whitelisted.
  		def micropost_params
    		params.require(:micropost).permit(:content, :user_id, :email, :tag)
  		end
end

app/helpers/microposts_helper.rb
module MicropostsHelper

	def wrap(content) 
		sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
	end

	private

		def wrap_long_string(text, max_width = 30)
			zero_width_space = "&#8203;"
			regex = /.{1,#{max_width}}/
			(text.length < max_width) ? text :
										text.scan(regex).join(zero_width_space)
		end

end

app/views/microposts/_mail.html.erb
<li>
	From<%= mail.sender_email %> [<%= mail.tag %>]&nbsp;:&nbsp; <%= mail.content %>
</li>

app/views/microposts/_micropost.html.erb
<li id="<%= micropost.id %>">
	<span class="content"><%= wrap(micropost.content) %></span>
	<em>
	<% tmp = micropost.count_votes %>
   	<%= tmp %> Vote
   	<% if current_user.can_vote_for?(micropost) %>
   	  | <%= link_to "Up", vote_micropost_path(micropost, value: 1, count: tmp), method: "post", remote: true %>
      | <%= link_to "Down", vote_micropost_path(micropost, value: -1, count: tmp), method: "post", remote: true %>
    <% elsif current_user.voted?(micropost) %>
      | <%= link_to "Cancel", delete_micropost_path(micropost, count: tmp), method: "delete", remote: true %>
    <% end %>
  	</em>
</li>

app/views/microposts/_micropost_form.html.erb
<%= form_for @micropost, remote: true do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<% # above code is equivalent to render partial: "shared/error_messages", locals: { object: f.object } %>
	<% # the variable f is a FormBuilder object that incorporates the knowledge about the model object represented by @micropost passed into form_for %>
	 
	<div class='row'>
		<div class="col-xs-6">
		<%= f.text_field :email, placeholder: "Email"%>
		</div>
		<div class='col-xs-6'>
		<select id="micropost_tag" name="micropost[tag]" class="form-control">
			
			<option value>Pick a tag</option>

		<% if @love_post.nil? %>
			<option value="love">General</option>
		<% end %>
			
			<option value="miss">Homework</option>

			<option value="apologize">Travel</option>

			<option value="thought">Research</option>
		</select>
		</div>
	</div>
	<%= f.text_area :content, placeholder: "I want to say..." %>
	<div class="row">
		<div class="col-xs-6">
			<label class="countdown"/>
		</div>
		<div class="col-xs-6">
			<%= f.submit "Send", class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/microposts/create.js.erb
$("#micropost_content").val('');
$("#micropost_email").val('');
$("#micropost_tag").val('Pick a tag');

var remaining = 500 - jQuery('#micropost_content').val().length;
jQuery('.countdown').text(remaining + ' character(s) remaining');

$('div#placeholder').html('<div id="notice" class="alert alert-info" style="height:85%;" ><%= flash[:notice] %></div>');

setTimeout(function(){
	$('div#placeholder').html('');
}, 5000);

<% if !@post.nil? %>
	<% publish_to "/messages/new" do %>
		$('#post').prepend('<%= j render @post %>');
	<% end %>
<% end %>

app/views/microposts/delete.js.erb
$('#<%= @micropost.id %>').replaceWith('<li id="<%= @micropost.id %>"><span class="content"><%= @micropost.content %></span><em><%= @count_delete %> Vote</em><% if current_user.can_vote_for?(@micropost) %> | <%= link_to "Up", vote_micropost_path(@micropost, value: 1, count: @count_delete), method: "post", remote: true %>| <%= link_to "Down", vote_micropost_path(@micropost, value: -1, count: @count_delete), method: "post", remote: true %><% end %></li>');

app/views/microposts/inbox.html.erb
<h1>Received Message</h1>
<p style="margin-left: 40px;">If someone send you a message with the same tag, you will see it here.
<ul class="microposts">
	<%= render partial: 'mail', collection: @mails %>
</ul>

app/views/microposts/new.html.erb
<% title("一pie即合") %>
<%= javascript_include_tag "microposts.js" %>
<div class="row">	
	<div class="col-xs-3">
		<% if current_user.inform == false%>
			<div  id="instruction">
			If you leave "email" field blank, we will publish your message publicly.
			<br>
			<%= link_to "Got it", user_path(@user, mode: false), method: 'put', remote: true%>
			
			</div>
		<% end %>
	</div>
	
	<div  class="col-xs-6">
		<div id="placeholder" style="height: 100px;"></div>
		<%= render 'micropost_form' %>
		<ul id="post" class="microposts">
		<%= render @feed_items %>
		</ul>
	</div>
	
	<%= will_paginate @feed_items %>
</div>

app/views/microposts/new.js.erb
//This makes micropost#new action responds to javescript request from getScript()
$('#post').append('<%= j render @feed_items %>');

//This will update pagination to current page
<% if @feed_items.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @feed_items %>');
<% else %>
	$('.pagination').remove();
<% end %>

app/views/microposts/vote.js.erb
$('#<%= @vote.micropost_id %>').replaceWith('<li id="<%= @vote.micropost_id %>"><span class="content"><%= @vote.micropost.content %></span><em><%= @count %> Vote</em> | <%= link_to "Cancel", delete_micropost_path(@vote.micropost, count: @count), method: "delete", remote: true %></li>');