config/routes.rb
# Entire routes.rb is calling draw method with do-end block
SampleApp::Application.routes.draw do

  devise_for :users, controllers: { confirmations: 'confirmations' }

  # From API: resources(*resources, &block)
  # * called splat operator. It indicates that mrore parameters may be passed to the function.
  # And those parameters are collected up and an array is created.
  # do...end or {} is called "block" which contains several lines of code and can be executed with "yield".
  # do...end for multi-lines blocks and {} for single line blocks
  # block is associated with method invocation. 
  # e.g. greet {put 'Hello'} invokes a call to greet method with block {put 'Hello'}.
  # Basically, when you create a method, you can have several yield statement. 
  # Then if you invoke that method with blcok, the block is executed.

  resources :sessions, only: [:new, :create, :destroy]
  resources(:microposts) do
    post :vote, on: :member
    delete :delete, on: :member
  end
  
  resources :users

  resources :password_resets
  
  root to: 'static_pages#home'
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/sendmessage', to: 'microposts#new'
  get '/help',    to: 'users#help'
  delete '/removepost', to: 'microposts#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Created by
		<a href="http://www.renren.com/274123839/profile">土豪</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About 一pie即合",   about_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="col-xs-12">
    <div class="navbar-header">
      <%= link_to "一pie即合", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <% if signed_in? %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Inbox", microposts_path %></li>
            <li class="dropdown" id="fat-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Message Sent", current_user %></li>
                <li><%= link_to "Setting", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", signout_path, method: "delete" %></li>
              </ul>
            </li>
          </ul>
      </div>
    <% else %>

          <%= form_tag sessions_path, class: "navbar-form navbar-right", role: "form" do %>
            <div class="form-group">
              <%= text_field_tag :email, params[:email], placeholder: "Email", class: "form-control"%>
            </div>
            <div class="form-group">
              <%= password_field_tag :password, params[:password], placeholder: "Password", class: "form-control" %>   
            </div>
              <%= button_tag "Login", class: "btn btn-default", id: "login_btn" %>
          <% end %>
    <% end %> 
    </div>          
  </div>
</div>

<!-- <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
   -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>一pie即合</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class="controller-<%= params[:controller] %>">
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert <%= bootstrap_class_for(key) %>"> <%= value %></div>
    <% end %>
    <%= yield %>
    <% if signed_in? %>
      <%= subscribe_to "/messages/new" %>
    <% end %>
    
  </div>
</body>
</html>